[package]

name = "rust-keepass"
version = "0.0.1"
authors = ["GrayFox <grayfox@outerhaven.de>", "Jan S. <hans@hannover.ccc.de>"]

[lib]
name = "rust-keepass"
path = "src/lib.rs"

test = true
doctest = true
doc = true
